Repository githubschool/first-prize, pull requests merged in 2021-09, with the labels that each got.

#17 gusshawstewart add caption
  _slides/02-gusshawstewart.md
Labels: documentation, enhancement, help wanted

#11 adding new caption
  _slides/06-emrakblt.md
Labels: documentation, new-coin

#18 selengokkaya add caption
  _slides/10-selengokkaya.md
Labels: enhancement
